# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97680c28ecf3040a653c39a55f5fdaa90e90da01d89b04e66347c7916358efdeef79bd6409b3b8ed68c58b8b9573bf16b12e3f5e2508bc15f4cb811f6586914f

test:
  secret_key_base: 78fe8332173dfd98e3cce3072cbcd1e771c28f33318543fa99c302bd4f8c820849b265dbbd32f41ef5fd46134526989be1f35d66c2762f47be64da9e481a735e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
